name: PHP Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP + Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Composer update
        run: composer update --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: vendor/bin/phpunit --colors=always
